In [4]:
import numpy as np

In [6]:
a=np.array([[1,2,3],[4,5,6]])

In [9]:
print(a, a.shape, a.size)

[[1 2 3]
 [4 5 6]] (2, 3) 6


In [12]:
print(np.arange(0,10,1,np.float16))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [13]:
b=np.arange(4)

In [15]:
print(b.sum(),b.min(),b.max())

6 0 3


In [16]:
print(b.mean())

1.5


In [17]:
print(a.sum(axis=0))

[5 7 9]


In [18]:
print(np.log(np.arange(1,10,2)))

[ 0.          1.09861229  1.60943791  1.94591015  2.19722458]


In [19]:
import root


ImportError: No module named 'root'