In [115]:
import numpy as np

#np.loadtxt(fname='inflammation-01.csv', delimiter=',')

import sys
# print 'version is', sys.version

def fahr_kelvin(temp):
    return ((temp-32)*(5.0/9.0))+273.15

fk = fahr_kelvin(90)
# print 'temperature in f is: ', fk

def kelvin_celc(temp):
    return temp - 273.15
# print kelvin_celc(fk)

def fahr_celc(temp):
    tempk = fahr_kelvin(temp)
    result = kelvin_celc(tempk)
    return result
#print fahr_celc(90)

def fence(original, wrapper):
    return str(wrapper) + str(original) + str(wrapper)
#print fence('name', '*')

def outer(s):
    return s[0] + s[-1]
#print outer('helium')

#print outer(fence('carbon', '+'))

def center(data, desired):
    return (data - data.mean()) + desired

#def main():
#   script = sys.argv[0]
#   filename = sys.argv[1]
#   data = np.loadtxt(filename, delimiter=',')
#   for m in data.mean(axis=1):
#       print m

#print center(z, 3)

#print 'original min, mean, and max are:', z.min(), z.mean(), z.max()
centered = center(z, 0)
#print 'min, mean, and and max of centered data are:', centered.min(), centered.mean(), centered.max()

#np.loadtxt(fname='inflammation-01.csv', delimiter=',')

def display(a=1, b=2, c=3):
    print 'a:', a, 'b:', b, 'c:', c

print 'no parameters:'
display()
print 'one parameter:'
display(55)
print 'two parameters:'
display(55, 66)

display(c = 56)

#help(np.loadtxt)

#data = np.loadtxt(fname= 'inflammation-01.csv', delimiter=',')

#def rescale(array):
#    """
#    Rescale values within array to be between 0.0 and 1.0
#    
#    :param array: numpy ndarray 
#    :return: rescaled ndarray 
#    """
#    return (array - array.min()) / float(array.max() - array.min())
#rescale(data)

a = np.arange(15).reshape(3, 5)
a
a.shape
a.dtype.name

print a


no parameters:
a: 1 b: 2 c: 3
one parameter:
a: 55 b: 2 c: 3
two parameters:
a: 55 b: 66 c: 3
a: 1 b: 2 c: 56
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
